// Dazz Cam Inspired Presets Specification
export const DAZZ_PRESETS = [
  {
    id: 'cpm35',
    name: 'CPM35',
    brand: '35mm Film',
    subtitle: 'Warm Portra 400',
    description: 'Warna hangat golden amber khas rol film 35mm dengan grain halus dan stempel tanggal oranye retro.',
    badgeColor: '#f59e0b',
    cssFilter: 'sepia(0.22) contrast(1.16) brightness(1.04) saturate(1.25) hue-rotate(-8deg)',
    grainIntensity: 0.22,
    vignetteIntensity: 0.25,
    lightLeak: 'warm-diagonal',
    dateStamp: {
      format: 'YY MM DD',
      color: '#ff6f00',
      font: 'Share Tech Mono',
    },
    frame: 'none',
  },
  {
    id: 'gr_d',
    name: 'GR D',
    brand: 'Street B&W',
    subtitle: 'Ricoh High-Contrast',
    description: 'Monokrom hitam-putih kontras tinggi dramatis dengan tekstur grain analog pekat khas kamera Ricoh GR.',
    badgeColor: '#e2e8f0',
    cssFilter: 'grayscale(1) contrast(1.75) brightness(0.96)',
    grainIntensity: 0.48,
    vignetteIntensity: 0.4,
    lightLeak: 'none',
    dateStamp: {
      format: 'YY MM DD',
      color: '#e2e8f0',
      font: 'Share Tech Mono',
    },
    frame: 'none',
  },
  {
    id: 'dispo',
    name: 'DISPO 90s',
    brand: 'Disposable Cam',
    subtitle: 'Flash Party 1998',
    description: 'Warna punchy dan kontras blitz tajam kamera sekali pakai tahun 90-an. Sangat pas untuk pesta malam!',
    badgeColor: '#ef4444',
    cssFilter: 'contrast(1.32) brightness(1.1) saturate(1.35) hue-rotate(6deg)',
    grainIntensity: 0.32,
    vignetteIntensity: 0.3,
    lightLeak: 'corner-glow',
    dateStamp: {
      format: 'YY MM DD',
      color: '#ff5500',
      font: 'Share Tech Mono',
    },
    frame: 'none',
  },
  {
    id: 'polaroid',
    name: 'INSTAX',
    brand: 'Instant Film',
    subtitle: 'Classic White Border',
    description: 'Tampilan foto polaroid vintage instan lengkap dengan bingkai putih klasik dan warna pastel lembut.',
    badgeColor: '#10b981',
    cssFilter: 'sepia(0.18) contrast(1.08) brightness(1.06) saturate(0.92)',
    grainIntensity: 0.18,
    vignetteIntensity: 0.2,
    lightLeak: 'none',
    dateStamp: {
      format: 'YYYY.MM.DD',
      color: '#262626',
      font: 'Plus Jakarta Sans',
      position: 'frame-bottom',
    },
    frame: 'polaroid',
  },
  {
    id: 'prism',
    name: 'PRISM 80s',
    brand: 'Retro Flare',
    subtitle: 'Golden Light Leak',
    description: 'Efek kebocoran cahaya vintage (light leak) warna jingga keemasan yang jatuh alami pada sudut foto.',
    badgeColor: '#ec4899',
    cssFilter: 'sepia(0.2) contrast(1.12) brightness(1.06) saturate(1.22) hue-rotate(-12deg)',
    grainIntensity: 0.2,
    vignetteIntensity: 0.18,
    lightLeak: 'intense-flare',
    dateStamp: {
      format: 'YY MM DD',
      color: '#ff7700',
      font: 'Share Tech Mono',
    },
    frame: 'none',
  },
  {
    id: 'ct28',
    name: 'CT28 VHS',
    brand: 'Camcorder',
    subtitle: 'Cyber 90s Tape',
    description: 'Efek pita kaset video handycam dengan garis scanline halus dan jam digital khas rekaman lawas.',
    badgeColor: '#06b6d4',
    cssFilter: 'contrast(1.2) brightness(1.04) saturate(1.18) hue-rotate(12deg)',
    grainIntensity: 0.28,
    vignetteIntensity: 0.25,
    lightLeak: 'scanlines',
    dateStamp: {
      format: 'VCR_CLOCK',
      color: '#00ff88',
      font: 'VT323',
    },
    frame: 'vhs',
  },
  {
    id: 'astia',
    name: 'ASTIA',
    brand: 'Fuji Slide',
    subtitle: 'Dreamy Bloom Pastel',
    description: 'Tone warna lembut, dreamy bloom, dan highlight creamy yang memanjakan warna kulit saat pesta.',
    badgeColor: '#8b5cf6',
    cssFilter: 'contrast(1.02) brightness(1.1) saturate(1.12) sepia(0.1)',
    grainIntensity: 0.15,
    vignetteIntensity: 0.15,
    lightLeak: 'soft-glow',
    dateStamp: {
      format: 'YY MM DD',
      color: '#ff8833',
      font: 'Share Tech Mono',
    },
    frame: 'none',
  },
  {
    id: 'clean',
    name: 'RAW HD',
    brand: 'Natural',
    subtitle: 'Clean & Crisp',
    description: 'Kamera jernih tanpa filter warna tambahan untuk hasil foto natural apa adanya.',
    badgeColor: '#64748b',
    cssFilter: 'none',
    grainIntensity: 0,
    vignetteIntensity: 0,
    lightLeak: 'none',
    dateStamp: {
      format: 'none',
      color: '#ffffff',
      font: 'Plus Jakarta Sans',
    },
    frame: 'none',
  },
]

export function getPresetById(id) {
  return DAZZ_PRESETS.find((p) => p.id === id) || DAZZ_PRESETS[0]
}
